import sys,os
os.system('pip install requests')
os.system("pip install cfonts")
os.system('pip install webbrowser')
os.system('pip install pyfiglet')
os.system("pip install random")
os.system("pip install bs4")
os.system("pip install rich")
os.system("pip install time")
os.system("pip install datetime")
os.system('pip install socket')
os.system('pip install instaloader')
os.system('pip install webbrowser')
os.system('pip install os')
os.system('pip install random')
os.system('pip install time')
os.system('pip install pyfiglet')
os.system('pip install json')
os.system("pip install uid")
os.system("pip install uuid")
print("تم التحميل جميع المكاتب المطلوبة الاداة")